using HotelManagement.Enums;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HotelManagement.Models.Entities
{
    public class Invoice : BaseEntity
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int InvoiceNo { get; set; } // Auto-generated by DB		

        public DateTime Date { get; set; }

        public InvoiceType Type { get; set; }

        [MaxLength(5)]
        public string Currency { get; set; }

        [MaxLength(100)]
        public string ReferenceNo { get; set; }

        [Required]
        public int CustomerId { get; set; } // FK to Customer
        public Customer Customer { get; set; }

        public InvoiceStatus Status { get; set; }

        [MaxLength(300)]
        public string? Note { get; set; }

        [Column(TypeName = "decimal(18,2)")]
        public decimal CurySubTotal { get; set; }

        [Column(TypeName = "decimal(18,2)")]
        public decimal SubTotal { get; set; }

        [Column(TypeName = "decimal(18,2)")]
        public decimal ServiceCharge { get; set; } // 10% of SubTotal

        [Column(TypeName = "decimal(18,2)")]
        public decimal GrossAmount { get; set; }

        [Column(TypeName = "decimal(18,2)")]
        public decimal Paid { get; set; }

        [Column(TypeName = "decimal(18,2)")]
        public decimal Balance { get; set; }

        public ICollection<InvoiceDetail> InvoiceDetails { get; set; }
        public ICollection<Payment>? Payments { get; set; }

    }
}
