using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HotelManagement.Models.Entities
{
	public class Invoice
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
		public int InvoiceNo { get; set; } // Auto-generated by DB

		[Required]
		public int OrderNo { get; set; } // FK to Order
		public Order Order { get; set; }

		public DateTime Date { get; set; }

		[Required, MaxLength(50)]
		public string Type { get; set; } // Restaurant | Room | Other

		[MaxLength(100)]
		public string ReferenceNo { get; set; }

		[Required]
		public int CustomerId { get; set; } // FK to Customer
		public Customer Customer { get; set; }

		[Column(TypeName = "decimal(18,2)")]
		public decimal SubTotal { get; set; }

		[Column(TypeName = "decimal(18,2)")]
		public decimal ServiceCharge { get; set; } // 10% of SubTotal

		[Column(TypeName = "decimal(18,2)")]
		public decimal GrossAmount { get; set; }

		[Column(TypeName = "decimal(18,2)")]
		public decimal Paid { get; set; }

		[Column(TypeName = "decimal(18,2)")]
		public decimal Balance { get; set; }

		public ICollection<InvoiceDetail> InvoiceDetails { get; set; }
	}
}
