using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HotelManagement.Models.Entities
{
	public class Order
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
		public int OrderNo { get; set; } // Auto-generated by DB

		public DateTime Date { get; set; }

		[Required]
		public int CustomerId { get; set; } // Foreign key
		public Customer Customer { get; set; }

		[Required]
		public int TableNo { get; set; }

		public bool IsFreeOfCharge { get; set; }
		public bool Dining { get; set; }

		[MaxLength(500)]
		public string? Notes { get; set; }

		public DateTime CreatedDate { get; set; }
		public int CreatedBy { get; set; } // EmployeeID
		public DateTime? ModifiedDate { get; set; }
		public int? ModifiedBy { get; set; } // EmployeeID

		[Column(TypeName = "decimal(18,2)")]
		public decimal SubTotal { get; set; }

		[Column(TypeName = "decimal(18,2)")]
		public decimal ServiceCharge { get; set; } 

		[Column(TypeName = "decimal(18,2)")]
		public decimal GrossAmount { get; set; }

        public List<OrderItem> OrderItems { get; set; } = new(); // MUST initialize
    }
}
